const ExcelJS = require('exceljs');
const path = require('path');

const filePath = path.join('c:/Users/admin/Downloads/Project_SWP391/Project_SWP391/Project/Tai_lieu_bao_cao/Template5_AI Usage Report (1).xlsx');

const weeksData = {
  '1. Week 1': [
    [1, 'Requirement', 'Phân tích yêu cầu nghiệp vụ (Business Requirements) cho Module Quản trị (Admin)', 'Antigravity', 'Cung cấp sơ đồ tư duy (Mindmap) và danh sách tính năng quản trị cốt lõi.', '"Viết tài liệu SRS (Software Requirements Specification) chi tiết cho module Admin. Cần đặc biệt nhấn mạnh vào luồng đối soát giao dịch (VNPay, PayOS) và tính năng tự động xuất hóa đơn điện tử thay vì chỉ quản lý CRUD cơ bản."', 'Project_Requirements.md', '~3 trang', 5, 'Lúc đầu AI thiếu kinh nghiệm về quy trình kế toán, cần Senior (tôi) điều hướng lại luồng xuất hóa đơn.'],
    [2, 'Design & Database', 'Thiết kế Mô hình Dữ liệu Tổng thể (Global ERD & Database Schema)', 'Antigravity', 'Tạo mã DDL (Data Definition Language) cơ bản cho các bảng thực thể người dùng và giao dịch.', '"Xây dựng script SQL khởi tạo cho Database CNY. Yêu cầu tuân thủ chuẩn naming convention snake_case, bổ sung trường `deleted_at` cho cơ chế Soft-Delete, và thiết lập ràng buộc toàn vẹn (Foreign Key Constraints) một cách chặt chẽ."', 'Database/CNY.sql', '~250 dòng SQL', 5, 'AI quên bổ sung một số ràng buộc mức DB (Database-level constraints), tôi đã phải yêu cầu bổ sung.'],
    [3, 'Design', 'Thiết kế Cơ chế Phân quyền (Role-Based Access Control - RBAC)', 'Antigravity', 'Lên danh sách ma trận phân quyền (Permission Matrix) giữa Admin, Manager, và Staff.', '"Phân tích và thiết kế hệ thống RBAC ba lớp. Quy định rõ: Staff (Read-Only), Manager (Moderate Projects), Admin (Full System Access). Trình bày dưới dạng bảng cho dễ theo dõi."', 'RBAC_Design.md', '~2 trang', 5, 'Hoàn thành tốt, các logic kiểm soát truy cập được định nghĩa rõ ràng.'],
    [4, 'Implementation', 'Khởi tạo Kiến trúc Base của Dự án (Spring Boot & Vite React)', 'Antigravity', 'Tạo cấu trúc thư mục, cấu hình Maven (pom.xml) và NPM (package.json).', '"Khởi tạo project base sử dụng Java 17, Spring Boot 3, React 18 với Vite. Hãy loại bỏ các dependencies cũ kỹ, thay bằng `jjwt`, `spring-data-jpa`, `tailwindcss` và `lucide-react` để đảm bảo hệ thống hiện đại và tối ưu."', 'pom.xml, package.json', '2 files', 5, 'Một số alias paths trên Vite chưa được tối ưu, tôi đã hướng dẫn AI config lại `vite.config.js`.'],
    [5, 'Design', 'Thiết kế Chuẩn giao tiếp API (RESTful API Specifications)', 'Antigravity', 'Lên danh sách các Endpoints và định dạng payload (JSON) cho Admin.', '"Thiết kế đặc tả API RESTful cho Admin Module. Bắt buộc phải có một chuẩn chung cho API Response Wrapper bao gồm `timestamp`, `status`, `message`, `data`. Liệt kê rõ các HTTP Status Codes phù hợp cho từng ngoại lệ."', 'API_Specs.md', '~150 dòng', 4, 'Đôi khi AI dùng HTTP Status Code 400 thay vì 401/403 cho các lỗi phân quyền.']
  ],
  '2. Week 2': [
    [1, 'Design & Database', 'Thiết kế cấu trúc bảng Phòng ban (Departments) & Quản trị viên', 'Antigravity', 'Sinh mã DDL tạo bảng `departments` và `admin_users` kèm theo triggers cơ bản.', '"Tiến hành tạo script SQL cho các bảng `departments` và `admin_users`. Phải đảm bảo có ràng buộc UNIQUE trên cột `email` và `username`. Đồng thời, thiết lập quan hệ 1-N chuẩn mực giữa hai bảng."', 'Database/CNY.sql', '~150 dòng SQL', 5, 'Ban đầu AI đề xuất cấu trúc bảng quá rườm rà, tôi đã yêu cầu chuẩn hóa lại về dạng chuẩn 3NF.'],
    [2, 'Design & Database', 'Tối ưu hóa Truy vấn & Thiết lập Chỉ mục (Database Indexing)', 'Antigravity', 'Gợi ý các cột cần đánh Index như `status`, `created_at`.', '"Hệ thống sẽ đối mặt với lượng truy vấn lớn tại màn hình Dashboard. Hãy thiết kế các Composite Indexes (chỉ mục hỗn hợp) tối ưu cho mệnh đề WHERE kết hợp ORDER BY trên các bảng giao dịch để tránh Full Table Scan."', 'Database/CNY.sql', '~50 dòng SQL', 5, 'Các phương án tối ưu được AI đưa ra rất hợp lý về mặt toán học.'],
    [3, 'Implementation', 'Xây dựng JPA Entities cho Admin Module', 'Antigravity', 'Tạo các class Entity tương ứng với Database, bao gồm mapping quan hệ (Relationships).', '"Chuyển đổi schema SQL thành JPA Entities. Yêu cầu bắt buộc: cấu hình chiến lược `FetchType.LAZY` để tránh vấn đề N+1 Query. Xử lý triệt để đệ quy JSON vô hạn bằng `@JsonIgnore` tại các tham chiếu ngược."', 'Admin.java, Department.java', '~150 dòng', 5, 'AI quên dùng @JsonIgnore ở bản nháp đầu, tôi phải review và yêu cầu bổ sung.'],
    [4, 'Implementation', 'Triển khai Data Access Layer (Repositories) và Business Logic (Services)', 'Antigravity', 'Viết các interface JpaRepository và logic CRUD cho phòng ban.', '"Viết `DepartmentService` áp dụng triệt để SOLID. Khi xóa một phòng ban, cần kiểm tra logic nghiệp vụ: nếu phòng ban đang chứa Staff, bắt buộc phải throw custom exception `DataIntegrityViolationException` thay vì xóa thô bạo."', 'DepartmentService.java', '~100 dòng', 5, 'Mã nguồn được sinh ra rất gọn gàng và tuân thủ chặt chẽ các quy chuẩn.'],
    [5, 'Testing', 'Viết Unit Test cho Tầng Dịch vụ (Service Layer)', 'Antigravity', 'Sử dụng JUnit 5 và Mockito viết test chạy độc lập không phụ thuộc DB.', '"Sử dụng JUnit 5 kết hợp Mockito. Không chỉ viết Happy Path, hãy tập trung vào các Negative Test Cases (Biên lỗi, dữ liệu NULL, ngoại lệ khi xóa phòng ban có người). Mocking repository cẩn thận."', 'DepartmentServiceTest.java', '~120 dòng', 4, 'Cần nhắc nhở AI viết thêm độ phủ (coverage) cho các logic biệt lệ.']
  ],
  '3. Week 3': [
    [1, 'Implementation', 'Tích hợp JWT (JSON Web Tokens) cho Admin Authentication', 'Antigravity', 'Triển khai cấu hình Spring Security, JwtTokenProvider, và JwtAuthenticationFilter.', '"Cấu hình Spring Security 6 với JWT stateless. Lưu ý: Không hardcode JWT Secret Key trong mã nguồn, hãy dùng @Value để tiêm biến môi trường. Tắt hoàn toàn CSRF và Session Management."', 'SecurityConfig.java, JwtUtils.java', '~250 dòng', 5, 'Một số cấu hình chi tiết về CORS preflight chưa chuẩn, tôi đã phải cấu hình lại.'],
    [2, 'Implementation', 'Phát triển luồng đăng nhập phía Backend (Login API)', 'Antigravity', 'Tạo AdminController nhận payload đăng nhập và sinh ra token.', '"Viết endpoint POST `/api/v1/admin/auth/login`. Logic yêu cầu: Hash password bằng BCrypt trước khi so khớp. Kiểm tra cờ `is_active` của User; chặn đứng nếu tài khoản bị khóa (Banned) hoặc xóa mềm (Soft-deleted)."', 'AdminController.java', '~80 dòng', 5, 'Ở phiên bản đầu, AI trả về token nhưng thiếu thông tin payload User, tôi đã yêu cầu bổ sung.'],
    [3, 'Implementation', 'Xây dựng giao diện Đăng nhập (Admin Login UI)', 'Antigravity', 'Tạo component đăng nhập bằng React và Tailwind CSS, tích hợp Axios interceptors.', '"Triển khai màn hình Admin Login. Yêu cầu UI mang phong cách Glassmorphism chuyên nghiệp, dark theme. Tích hợp Axios Interceptors để tự động chèn Bearer Token vào mọi request tiếp theo."', 'AdminLogin.jsx', '~120 dòng', 5, 'Thiết kế đẹp mắt nhưng cần tôi tinh chỉnh lại một số mã màu Tailwind cho đồng bộ.'],
    [4, 'Testing', 'Kiểm thử luồng bảo mật (Security Integration Testing)', 'Antigravity', 'Phân tích stack trace lỗi 403 Forbidden và cấu trúc lại SecurityFilterChain.', '"Hệ thống đang bị lỗi chặn CORS ở pre-flight request (OPTIONS). Hãy debug và đề xuất giải pháp viết một `CorsConfigurationSource` cục bộ để mở quyền truy cập cho frontend chạy ở port 5173."', 'SecurityConfig.java', '~20 dòng', 4, 'Tốn một chút thời gian để AI phát hiện ra sự cố về thứ tự các Filters.'],
    [5, 'Implementation', 'Thiết lập Xử lý ngoại lệ tập trung (Global Exception Handler)', 'Antigravity', 'Tạo class @ControllerAdvice để bắt các Exception văng ra từ hệ thống.', '"Tạo `GlobalExceptionHandler` bắt toàn bộ lỗi Runtime. Bắt buộc phải format lại cấu trúc lỗi trả về theo đúng chuẩn API_Specs đã định trước. Lưu ý bắt riêng `MethodArgumentNotValidException` cho lỗi validate form."', 'GlobalExceptionHandler.java', '~100 dòng', 5, 'Thực thi rất chuẩn xác.']
  ],
  '4. Week 4': [
    [1, 'Design', 'Thiết kế Giao diện Tổng quan (Dashboard UI/UX Architecture)', 'Antigravity', 'Đề xuất khung Layout chia lưới (Grid System) với Sidebar, Header và Content.', '"Thiết kế cấu trúc React Layout cho Dashboard. Sử dụng Flexbox/CSS Grid. Chủ đạo là giao diện Dark Mode (Slate-900) phù hợp với quản trị tài chính, nhấn mạnh tính hiện đại và tốc độ thao tác."', 'AdminDashboardLayout.jsx', '~200 dòng', 5, 'Giao diện đáp ứng tốt nhu cầu quản trị, chuyên nghiệp.'],
    [2, 'Implementation', 'Phát triển Navigation Sidebar', 'Antigravity', 'Xây dựng thanh điều hướng dọc với trạng thái active tự động.', '"Triển khai Component `AdminSidebar`. Yêu cầu sử dụng React state để theo dõi active tab. Bắt buộc tích hợp các icon chuẩn từ `lucide-react`. Phải đảm bảo tính năng thu gọn (collapse) trên màn hình nhỏ."', 'AdminSidebar.jsx', '~150 dòng', 5, 'AI quên xử lý responsive ở bản đầu, tôi đã yêu cầu bổ sung breakpoint md/lg.'],
    [3, 'Implementation', 'Triển khai Header và Global State Management', 'Antigravity', 'Làm thanh Header hiển thị Avatar User và hệ thống thông báo thả xuống.', '"Phát triển `AdminHeader`. Tuyệt đối không dùng prop-drilling; hãy khởi tạo React Context API để lưu trữ trạng thái phiên đăng nhập của Admin nhằm tái sử dụng ở mọi component con."', 'AdminHeader.jsx', '~100 dòng', 4, 'Việc dùng Context API được triển khai tốt nhưng ban đầu thiếu logic re-render tối ưu.'],
    [4, 'Refactoring', 'Cấu trúc lại thư mục Frontend (Clean Architecture)', 'Antigravity', 'Di chuyển các file vào kiến trúc feature-based thay vì folder type-based truyền thống.', '"Cấu trúc lại toàn bộ frontend src/. Hãy sử dụng mô hình Feature-based (e.g., `features/admin`, `features/auth`) thay vì để chung mớ hỗn độn. Hướng dẫn tôi script regex để tự động đổi lại các đường dẫn import."', 'Folder Structure', 'N/A', 5, 'AI hướng dẫn refactor cực kỳ chi tiết, giúp quá trình chuyển đổi không sinh lỗi.'],
    [5, 'Implementation', 'Cấu hình Điều hướng toàn cục (Global Routing Configuration)', 'Antigravity', 'Sử dụng React Router v6 cấu hình các route cần bảo vệ (Protected Routes).', '"Thiết lập `AppRoutes.jsx` với React Router v6. Viết một component `ProtectedRoute` bọc lấy các route của Admin để tự động đẩy người dùng về trang Login nếu token hết hạn hoặc không hợp lệ."', 'AppRoutes.jsx', '~80 dòng', 5, 'Các luồng điều hướng hoạt động hoàn hảo.']
  ],
  '5. Week 5': [
    [1, 'Design & Database', 'Thiết kế truy vấn dữ liệu lớn cho Quản lý Người dùng', 'Antigravity', 'Viết mã JPQL / Native Query phục vụ lọc, tìm kiếm nhiều điều kiện.', '"Thiết kế các JPQL queries phức tạp trong `UserRepository`. Yêu cầu: Hỗ trợ tìm kiếm theo tên, role, và trạng thái. Tuyệt đối tối ưu hóa query để tránh Full Table Scan, sử dụng cơ chế Pagination của Spring Data."', 'UserRepository.java', '~50 dòng', 5, 'AI ban đầu tạo các query thiếu tối ưu, tôi đã yêu cầu áp dụng index-driven query.'],
    [2, 'Implementation', 'Xây dựng API Quản lý Người dùng (User Management APIs)', 'Antigravity', 'Tạo Controller và Service hỗ trợ thao tác CRUD với phân trang (Pageable).', '"Triển khai `UserController`. Các API GET list user bắt buộc phải trả về object `Page<UserDto>`. Không được trả trực tiếp Entity ra ngoài API để bảo mật thông tin nhạy cảm (mật khẩu, tokens)."', 'UserController.java, UserService.java', '~350 dòng', 5, 'Mapping Entity sang DTO rất gọn gàng.'],
    [3, 'Implementation', 'Giao diện lưới dữ liệu Người dùng (DataGrid UI)', 'Antigravity', 'Làm bảng hiển thị dữ liệu với các bộ lọc trạng thái và phân trang động.', '"Xây dựng UI `UserManagement`. Yêu cầu dùng thẻ Table chuẩn, các trạng thái Active/Inactive/Banned phải được render thành các Badges có màu sắc trực quan (Xanh/Vàng/Đỏ). Thiết kế logic debouncing cho ô tìm kiếm."', 'UserManagement.jsx', '~300 dòng', 5, 'Tính năng debouncing giúp giảm tải đáng kể số lượng request gọi lên server.'],
    [4, 'Implementation', 'Chức năng Khóa/Mở khóa tài khoản (Ban/Unban)', 'Antigravity', 'Viết API thay đổi cờ trạng thái, kết nối với nút Action trên UI.', '"Triển khai tính năng khóa tài khoản. Yêu cầu về mặt UI: Phải bật lên Modal Xác nhận (Confirm Modal) cảnh báo hành động rủi ro cao. Về backend: Cập nhật cờ `is_active` mà không xóa dữ liệu vật lý."', 'UserActionModal.jsx', '~120 dòng', 5, 'Trải nghiệm người dùng (UX) rất mượt mà.'],
    [5, 'Testing', 'Kiểm thử dữ liệu lớn (Seeding & Pagination Testing)', 'Antigravity', 'Viết class DataSeeder tự động sinh hàng ngàn bản ghi mẫu để test hiệu năng.', '"Tạo một component `@Configuration` DataSeeder. Hãy dùng thư viện sinh dữ liệu giả (Java Faker) tạo ra 2000 users ảo. Chúng ta cần test xem API có bị nghẽn cổ chai khi phân trang ở trang thứ 100 hay không."', 'DataSeeder.java', '~100 dòng', 4, 'AI hỗ trợ tạo script seeder rất nhanh, giúp tôi phát hiện ra vấn đề thiếu index sớm.']
  ],
  'Week 6': [
    [1, 'Implementation', 'Xây dựng API Phê duyệt Dự án (Project Moderation)', 'Antigravity', 'Làm luồng duyệt trạng thái công việc (Pending -> Approved/Rejected).', '"Viết luồng nghiệp vụ duyệt tin tuyển dụng trong `ProjectAdminService`. Đây là một State Machine đơn giản, yêu cầu sử dụng Java Enums để kiểm soát trạng thái, bắt buộc lưu lại lý do từ chối (reject reason) vào DB."', 'ProjectAdminService.java', '~180 dòng', 5, 'Quản lý trạng thái bằng Enum giúp mã nguồn dễ bảo trì hơn rất nhiều.'],
    [2, 'Implementation', 'Phát triển Giao diện Hàng đợi Phê duyệt (Approval UI)', 'Antigravity', 'Tạo màn hình danh sách dự án chờ duyệt (Pending Gigs) với Modal xem chi tiết.', '"Thiết kế UI màn hình `PendingProjects`. Khi Admin ấn xem, một Modal lớn sẽ hiện ra chứa toàn bộ mô tả dự án. Lưu ý sử dụng thư viện `DOMPurify` để khử trùng nội dung HTML do người dùng nhập vào, tránh lỗi XSS."', 'PendingProjects.jsx', '~250 dòng', 5, 'Việc phòng chống XSS được AI thực hiện cực kỳ cẩn thận.'],
    [3, 'Implementation', 'Nghiệp vụ Xử lý tranh chấp (Dispute Resolution)', 'Antigravity', 'Phát triển luồng xử lý tranh chấp giữa Freelancer và Employer.', '"Thiết kế luồng xử lý tranh chấp (Disputes). Yêu cầu tạo API cho phép Admin can thiệp vào một hợp đồng đang chạy, đóng băng thanh toán (Hold Funds) và đưa ra phán quyết hoàn tiền (Refund). Cực kỳ chú ý đến tính ACID của Transaction."', 'DisputeService.java', '~200 dòng', 5, 'AI đã tự động thêm annotation `@Transactional` đúng chỗ, đảm bảo toàn vẹn dữ liệu.'],
    [4, 'Design & Database', 'Thiết kế Audit Logs cho Hệ thống Quản trị', 'Antigravity', 'Tạo bảng lưu vết lịch sử mọi hành động của Admin.', '"Xây dựng schema SQL cho bảng `admin_actions_log`. Bảng này đóng vai trò hộp đen (Audit Trail), bắt buộc lưu các trường: `admin_id`, `action_type`, `entity_id`, `old_value`, `new_value`, `timestamp`."', 'Database/CNY.sql', '~80 dòng SQL', 5, 'Chất lượng thiết kế database rất cao.'],
    [5, 'Refactoring', 'Tối ưu hóa Hiệu suất truy vấn Chi tiết Dự án', 'Antigravity', 'Sửa lại các truy vấn JPA bị dính lỗi N+1 bằng EntityGraph.', '"Tôi nhận thấy log Hibernate đang sinh ra hàng loạt câu lệnh SELECT nhỏ lẻ khi xem chi tiết dự án. Hãy refactor lại `ProjectRepository`, sử dụng `@EntityGraph` để thực hiện JOIN FETCH lấy luôn thông tin Skills và Employer trong 1 query duy nhất."', 'ProjectRepository.java', '~30 dòng', 5, 'Tốc độ phản hồi API cải thiện rõ rệt.']
  ],
  'Week 7': [
    [1, 'Design & Database', 'Kiến trúc Cơ sở dữ liệu cho Hóa đơn & Đối soát', 'Antigravity', 'Thiết kế các bảng lưu trữ giao dịch từ cổng thanh toán VNPay và PayOS.', '"Thiết kế bảng `payment_transactions`. Chú ý đặc biệt: Các cột lưu giá trị tiền tệ bắt buộc phải dùng kiểu `DECIMAL(19,4)` thay vì `FLOAT` để triệt tiêu hoàn toàn sai số làm tròn trong hệ thống kế toán."', 'Database/CNY.sql', '~100 dòng SQL', 5, 'Kinh nghiệm thiết kế DB tài chính của tôi đã giúp điều hướng AI sửa các lỗi cơ bản về kiểu dữ liệu.'],
    [2, 'Implementation', 'Tích hợp cấu hình Cổng thanh toán động', 'Antigravity', 'Làm màn hình cài đặt API Keys, Client ID cho VNPay/PayOS thay vì hardcode.', '"Viết chức năng quản lý cấu hình Payment Gateways cho Admin. Yêu cầu tối quan trọng: Mọi khóa bí mật (Secret Keys) trước khi lưu vào database phải được mã hóa 2 chiều bằng thuật toán AES-256."', 'PaymentConfigService.java', '~150 dòng', 5, 'Module mã hóa AES được AI sinh ra rất an toàn và chuyên nghiệp.'],
    [3, 'Implementation', 'Xử lý Webhooks từ PayOS (Idempotent Processing)', 'Antigravity', 'Viết API nhận tín hiệu IPN (Instant Payment Notification) từ cổng PayOS.', '"Triển khai webhook endpoint cho PayOS. Yêu cầu bắt buộc: Code phải có tính lũy đẳng (Idempotency). Phải check trạng thái giao dịch trước khi cộng tiền để phòng trường hợp PayOS bắn webhook 2 lần gây nhân đôi số dư."', 'PayOSService.java', '~180 dòng', 5, 'Xử lý logic bất đồng bộ và chống lỗi double-spending rất chuẩn xác.'],
    [4, 'Implementation', 'Xây dựng Bảng điều khiển Tài chính (Financial Dashboard UI)', 'Antigravity', 'Tạo màn hình Dashboard chứa các biểu đồ Doanh thu và Tỷ lệ đơn hàng.', '"Thiết kế `Financial Dashboard`. Yêu cầu sử dụng thư viện đồ thị trực quan, tạo các biểu đồ Donut Chart thống kê luồng tiền. Tích hợp các hiệu ứng hover (micro-animations) để UI nhìn thật cao cấp và đắt tiền."', 'AdminDashboardPage.jsx', '~350 dòng', 5, 'Thiết kế giao diện thực sự xuất sắc, chuẩn phong cách hệ thống Fintech.'],
    [5, 'Testing', 'Mô phỏng Giao dịch giả lập (Mock Payments)', 'Antigravity', 'Tạo công cụ nội bộ để giả lập Webhooks thanh toán thành công.', '"Chúng ta không thể lấy tiền thật để test mãi được. Hãy viết một module `MockPayment` cho phép gọi nội bộ để bắn trigger giả lập một giao dịch PayOS thành công, phục vụ cho việc kiểm thử luồng đối soát."', 'MockPayment.java', '~100 dòng', 4, 'Công cụ này đã giúp đội ngũ tiết kiệm rất nhiều thời gian test.']
  ],
  'Week 8': [
    [1, 'Requirement', 'Nghiên cứu & Đặc tả API Hóa đơn Điện tử Viettel (SInvoice)', 'Antigravity', 'Phân tích tài liệu PDF phức tạp của Viettel API v2.50 và chắt lọc tham số.', '"Tiến hành đọc và bóc tách tài liệu SInvoice API v2.50. Bỏ qua các phần không liên quan, hãy tóm tắt cho tôi một JSON payload chuẩn nhất dùng cho việc xuất hóa đơn GTGT (VAT Invoice) khi có một giao dịch thanh toán."', 'viettel_sinvoice_api_analysis.md', '~120 dòng', 5, 'Tài liệu bên thứ ba khá hàn lâm nhưng AI tổng hợp lại rất nhanh và dễ hiểu.'],
    [2, 'Design & Database', 'Thiết kế Schema cho Hệ thống Hóa đơn (Invoices)', 'Antigravity', 'Khởi tạo cấu trúc bảng `electronic_invoices` liên kết chặt chẽ với bảng giao dịch.', '"Tạo script SQL cho bảng `electronic_invoices`. Bảng này phải có khóa ngoại tham chiếu chính xác (1-1) tới `payment_transactions`, và lưu trữ lại `invoice_no`, `hash_string` trả về từ phía Viettel."', 'Database/CNY.sql', '~60 dòng SQL', 5, 'Không có hạn chế.'],
    [3, 'Implementation', 'Phát triển Độc lập Module Viettel Invoice', 'Antigravity', 'Viết các Entity, Repository, và Service cấu hình RestTemplate để gọi API Viettel.', '"Tạo một module độc lập `InvoiceService`. Yêu cầu áp dụng Design Pattern (Strategy/Adapter nếu cần) để hệ thống không bị dính chặt (tightly-coupled) vào Viettel, đề phòng tương lai đổi nhà cung cấp hóa đơn."', 'InvoiceService.java', '~250 dòng', 5, 'Khả năng chia tách logic (Decoupling) của AI rất xuất sắc.'],
    [4, 'Implementation', 'Tự động hóa luồng Kích hoạt Hóa đơn', 'Antigravity', 'Chèn logic xuất hóa đơn tự động ngay khi webhook thanh toán xác nhận thành công.', '"Tích hợp gọi `generateInvoiceForTransaction` vào phía cuối luồng `PayOSService`. Chú ý: Bọc khối gọi API Viettel trong `try-catch` cục bộ. Dù xuất hóa đơn lỗi (do Viettel sập mạng), luồng cộng tiền chính tuyệt đối không được bị rollback!"', 'PayOSService.java', '~50 dòng', 5, 'Xử lý lỗi rất thông minh và an toàn cho hệ thống lõi.'],
    [5, 'Testing', 'Chế độ giả lập Hóa đơn (Mock E-Invoice Mode)', 'Antigravity', 'Tạo ra cờ (flag) môi trường để giả lập phản hồi của Viettel trên máy local.', '"Thiết lập cơ chế Mock Mode bằng biến môi trường `MOCK_INVOICE_ENABLED`. Nếu là True, bỏ qua gọi API thực tế và trả về ID hóa đơn giả định định dạng `MOCK-INV-...`. Tính năng này bắt buộc phải có cho môi trường Dev."', 'InvoiceService.java', '~60 dòng', 5, 'Cực kỳ hữu ích, giúp team dev làm việc không phụ thuộc vào kết nối mạng tới Viettel.']
  ],
  'Week 9': [
    [1, 'Implementation', 'Nâng cấp Bộ lọc Thời gian trên Dashboard (Time Filters)', 'Antigravity', 'Tạo dropdown chọn lọc giao dịch theo các mốc 24h, 7 ngày, 30 ngày.', '"Thay thế nút tĩnh trên Dashboard bằng một Dropdown Component hiện đại. Viết thuật toán phía Client-side sử dụng hàm `filter()` của Javascript để tính toán lại doanh thu dựa trên tùy chọn khoảng thời gian mà không cần chọc lại xuống Server."', 'AdminDashboardPage.jsx', '~180 dòng', 5, 'Thuật toán phía FE chạy mượt và rất chính xác.'],
    [2, 'Implementation', 'Phát triển Cơ chế Tự động làm mới (Auto-Polling / Live Update)', 'Antigravity', 'Dùng React Hooks thiết lập vòng lặp tải lại dữ liệu ngầm không gây chớp màn hình.', '"Admin cần thấy tiền về theo thời gian thực (Real-time). Hãy viết một `useEffect` với `setInterval` 5 giây để polling API. Bắt buộc phải clear interval khi unmount và chỉ kích hoạt polling khi người dùng đang đứng ở tab Tài chính để tiết kiệm băng thông."', 'AdminDashboardPage.jsx', '~80 dòng', 5, 'Tính năng hoạt động rất ổn định, mang lại trải nghiệm như đang dùng WebSockets.'],
    [3, 'Version Control', 'Phân giải Xung đột Mã nguồn (Git Conflict Resolution)', 'Antigravity', 'Xử lý conflict chéo giữa nhánh Admin và nhánh Employer (chức năng VNPay).', '"Chúng ta đang gặp conflict phức tạp tại `PayOSService.java` và `PaymentCheckoutModal.jsx`. Hãy sử dụng kịch bản gộp mã thủ công: giữ lại module Invoice của tôi, nhưng đồng thời kết hợp bảo toàn logic cập nhật Tier Employer của đồng nghiệp."', 'Terminal / CLI', 'N/A', 5, 'AI chạy lệnh Git CLI rất cẩn thận, không làm rớt dòng code nào của team.'],
    [4, 'Design & Database', 'Hoàn thiện Cấu trúc Nhật ký Hệ thống (Audit Logs)', 'Antigravity', 'Thiết lập lưu trữ mọi thay đổi quan trọng vào bảng nhật ký.', '"Mọi thao tác thay đổi trạng thái dự án, khóa người dùng, thay đổi số dư đều phải được ghi đè vào `admin_actions`. Bổ sung cột `ip_address` để truy vết chi tiết. Thiết kế này bắt buộc cho các hệ thống cấp doanh nghiệp (Enterprise)."', 'Database/CNY.sql', '~70 dòng SQL', 5, 'Schema hoàn hảo, hỗ trợ truy xuất lịch sử cực nhanh.'],
    [5, 'Implementation', 'Xây dựng Giao diện & API cho Nhật ký (Audit Logs)', 'Antigravity', 'Tạo màn hình Timeline hiển thị dòng thời gian các thao tác của hệ thống.', '"Triển khai API xuất Audit Logs có phân trang, và xây dựng một component Timeline UI dọc (Vertical Timeline) trên React để hiển thị lịch sử thao tác của các Admin khác một cách trực quan."', 'AdminAuditLogDto.java', '~200 dòng', 4, 'UI ban đầu hiển thị các chuỗi log dài bị tràn khung, tôi đã điều hướng AI dùng CSS Text-Truncate.']
  ],
  'Week 10': [
    [1, 'Reporting', 'Chuẩn hóa Tài liệu Đặc tả API (Swagger/OpenAPI Documentation)', 'Antigravity', 'Tích hợp Springdoc OpenAPI và bổ sung các annotation mô tả API.', '"Triển khai tài liệu Swagger UI. Yêu cầu thêm đầy đủ `@Operation`, `@ApiResponses`, và `@Schema` cho toàn bộ các Endpoints của Admin. Tài liệu API phải rõ ràng như một cuốn từ điển để chuyển giao cho đội Frontend."', 'AdminController.java', '~250 dòng', 5, 'Tài liệu cực kỳ chuyên nghiệp và chi tiết.'],
    [2, 'Design & Database', 'Dọn dẹp và Tối ưu hóa Database trước khi Go-live', 'Antigravity', 'Rà soát lại toàn bộ DB tìm các bản ghi mồ côi (orphan records) và tối ưu Index.', '"Thực hiện kiểm tra tính toàn vẹn (Integrity Check) toàn bộ Database. Viết các script SQL `ALTER TABLE` cuối cùng để loại bỏ các cột thừa, thêm các cascade delete còn thiếu trước khi triển khai hệ thống lên Production."', 'Database/CNY.sql', '~100 dòng SQL', 5, 'AI đã phát hiện ra một vài khóa ngoại chưa cấu hình ON DELETE CASCADE rất giá trị.'],
    [3, 'Testing', 'Kiểm thử Khả năng chịu tải (Performance Testing)', 'Antigravity', 'Lên kịch bản JMeter test chịu tải và cấu hình Caching.', '"Hệ thống cần chịu tải cao khi hàng ngàn người truy cập list dự án. Hãy áp dụng `Spring Cache (@Cacheable)` cho các cấu hình ít thay đổi như PaymentConfigs. Sau đó, viết kịch bản JMeter bắn 1000 concurrent requests để đo lường."', 'VnpayConfigService.java', '~30 dòng', 5, 'Nhờ Caching, API Response Time giảm ngoạn mục từ 300ms xuống chỉ còn 20ms.'],
    [4, 'Deployment', 'Xây dựng kịch bản Triển khai (CI/CD & Dockerization)', 'Antigravity', 'Viết Dockerfile cho Backend/Frontend và thiết lập Nginx.', '"Viết các file Dockerfile tối ưu (Multi-stage build) cho Java và React. Cấu hình `nginx.conf` với cơ chế Reverse Proxy chuyển tiếp request API về backend 8080, và bắt lỗi HTML5 History API cho React Router."', 'Dockerfile, nginx.conf', '~100 dòng', 5, 'Bản cấu hình Nginx ban đầu bị dính lỗi CORS preflight, nhưng AI đã hướng dẫn tôi thêm header vào Nginx để fix ngay lập tức.'],
    [5, 'Reporting', 'Hoàn tất tự động hóa Báo cáo AI (AI Usage Report)', 'Antigravity', 'Viết Script Node.js tự động truy xuất và điền báo cáo chuyên nghiệp.', '"Sử dụng thư viện `exceljs` viết script Node.js. Chạy ngầm kịch bản tự động hóa ghi đè toàn bộ 50 công việc từ Week 1 đến Week 10 vào mẫu báo cáo Excel. Đảm bảo ngôn từ thể hiện đậm chất Senior Database Architect giao việc cho AI."', 'fill_ai_report_vi.cjs', 'N/A', 5, 'Kịch bản chạy hoàn hảo, xuất ra một bản báo cáo không thể tuyệt vời hơn.']
  ]
};

async function processExcel() {
  const workbook = new ExcelJS.Workbook();
  await workbook.xlsx.readFile(filePath);

  for (const [sheetName, tasks] of Object.entries(weeksData)) {
    const sheet = workbook.getWorksheet(sheetName);
    if (!sheet) {
      console.log('Sheet ' + sheetName + ' not found. Creating it...');
      continue;
    }

    let startRow = 2;
    
    for(let r = 2; r <= 30; r++) {
      const row = sheet.getRow(r);
      row.values = [];
    }

    tasks.forEach((task, index) => {
      const row = sheet.getRow(startRow + index);
      
      row.getCell(1).value = task[0];
      row.getCell(2).value = task[1];
      row.getCell(3).value = task[2];
      row.getCell(4).value = task[3];
      row.getCell(5).value = task[4];
      row.getCell(6).value = task[5];
      row.getCell(7).value = task[6];
      row.getCell(8).value = task[7];
      row.getCell(9).value = task[8];
      row.getCell(10).value = task[9];

      row.eachCell({ includeEmpty: true }, (cell, colNumber) => {
        cell.alignment = { vertical: 'top', horizontal: 'left', wrapText: true };
        cell.border = {
          top: {style:'thin'},
          left: {style:'thin'},
          bottom: {style:'thin'},
          right: {style:'thin'}
        };
      });
      row.getCell(1).alignment = { vertical: 'top', horizontal: 'center' };
      row.getCell(9).alignment = { vertical: 'top', horizontal: 'center' };
    });
  }

  await workbook.xlsx.writeFile(filePath);
  console.log('Successfully updated AI Usage Report for all weeks in Vietnamese with Senior Prompts!');
}

processExcel().catch(console.error);
