# ==========================================
# SPRING RUNTIME SERVER CONFIG
# ==========================================
server.port=8080
server.servlet.context-path=/api

# ==========================================
# MICROSOFT SQL SERVER DATASOURCE (CNY.sql)
# ==========================================
spring.datasource.url=jdbc:sqlserver://localhost:1433;databaseName=CNY;encrypt=true;trustServerCertificate=true
spring.datasource.username=sa
spring.datasource.password=sa
spring.datasource.driver-class-name=com.microsoft.sqlserver.jdbc.SQLServerDriver

# ==========================================
# JPA / HIBERNATE ORM CONFIGURATION
# ==========================================
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.SQLServer2016Dialect

# ==========================================
# JACKSON CONFIGURATION FOR DATE-TIME
# ==========================================
spring.jackson.serialization.write-dates-as-timestamps=false

# ==========================================
# EMAIL CONFIGURATION (Gmail SMTP)
# ==========================================
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=hihihahahohoaaa@gmail.com
spring.mail.password=ahjhbhxryhacikub
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

# ==========================================
# FILE UPLOAD MULTIPART CONFIGURATION
# ==========================================
spring.servlet.multipart.max-file-size=20MB
spring.servlet.multipart.max-request-size=20MB

# ==========================================
# VIETQR ACCOUNT LOOKUP API CREDENTIALS
# Đăng ký tại: https://my.vietqr.io
# ==========================================
vietqr.client-id=70eda2d1-7cfe-48de-a6e0-80d9f27b3cd4
vietqr.api-key=167341ed-40bb-4c3f-9a54-d5c74f4c8212
vietqr.checksum-key=e58d1f9fbb7007ae784145f85702d5c8222e3bc5b4abca7f9196588fb66352f9
vietqr.lookup-url=https://api.vietqr.io/v2/lookup

# PAYOS API CREDENTIALS
payos.client-id=70eda2d1-7cfe-48de-a6e0-80d9f27b3cd4
payos.api-key=167341ed-40bb-4c3f-9a54-d5c74f4c8212
payos.checksum-key=e58d1f9fbb7007ae784145f85702d5c8222e3bc5b4abca7f9196588fb66352f9

# ==========================================
# VNPAY API CREDENTIALS
# ==========================================
vnpay.tmn-code=DEMO2019
vnpay.hash-secret=9A7F11E55E1C3806E0528B65355AA05C
vnpay.vnp-url=https://sandbox.vnpayment.vn/paymentv2/vpcpay.html
vnpay.return-url=http://localhost:8080/api/payment/vnpay-return
