
IF NOT EXISTS (SELECT * FROM sysobjects WHERE name='api_frequency_stat' and xtype='U')
CREATE TABLE api_frequency_stat (
    id BIGINT IDENTITY(1,1) PRIMARY KEY,
    name NVARCHAR(255),
    path NVARCHAR(255),
    total INT,
    success INT,
    error400 INT,
    error_customer INT,
    error_system INT
);

TRUNCATE TABLE api_frequency_stat;
INSERT INTO api_frequency_stat (name, path, total, success, error400, error_customer, error_system) VALUES (N'Face mask V4', N'/ai/v4/face/mask', 0, 0, 0, 0, 0);
INSERT INTO api_frequency_stat (name, path, total, success, error400, error_customer, error_system) VALUES (N'/ai/v5/card/liveness', N'/ai/v5/card/liveness', 0, 0, 0, 0, 0);
INSERT INTO api_frequency_stat (name, path, total, success, error400, error_customer, error_system) VALUES (N'AI V4 Web Standard Face Liveness', N'/ai/v4/web/standard/face/liveness', 0, 0, 0, 0, 0);
INSERT INTO api_frequency_stat (name, path, total, success, error400, error_customer, error_system) VALUES (N'/faceid-service/v2/customer/add-update', N'/faceid-service/v2/customer/add-update', 0, 0, 0, 0, 0);
INSERT INTO api_frequency_stat (name, path, total, success, error400, error_customer, error_system) VALUES (N'tt17 ocr', N'/aitt17-service/v1/ocr/id', 0, 0, 0, 0, 0);
INSERT INTO api_frequency_stat (name, path, total, success, error400, error_customer, error_system) VALUES (N'Web v2 card liveness', N'/ai/v2/web/card/liveness', 0, 0, 0, 0, 0);
INSERT INTO api_frequency_stat (name, path, total, success, error400, error_customer, error_system) VALUES (N'Face one', N'/ai/v1/face/one', 0, 0, 0, 0, 0);
INSERT INTO api_frequency_stat (name, path, total, success, error400, error_customer, error_system) VALUES (N'Add face ereception', N'/face-service/face/add-ereception', 0, 0, 0, 0, 0);
INSERT INTO api_frequency_stat (name, path, total, success, error400, error_customer, error_system) VALUES (N'Web v1 card liveness', N'/ai/v1/web/card/liveness', 0, 0, 0, 0, 0);
INSERT INTO api_frequency_stat (name, path, total, success, error400, error_customer, error_system) VALUES (N'Face liveness 3d v4', N'/ai/v4/face/liveness-3d', 0, 0, 0, 0, 0);
INSERT INTO api_frequency_stat (name, path, total, success, error400, error_customer, error_system) VALUES (N'Ocr id front', N'/ai/v1/ocr/id/front', 0, 0, 0, 0, 0);
INSERT INTO api_frequency_stat (name, path, total, success, error400, error_customer, error_system) VALUES (N'Photo ocr id V4', N'/ai/v4/photo/ocr/id', 0, 0, 0, 0, 0);
INSERT INTO api_frequency_stat (name, path, total, success, error400, error_customer, error_system) VALUES (N'CIC customer face search', N'/cic-service/v1/customer-face/search', 0, 0, 0, 0, 0);
INSERT INTO api_frequency_stat (name, path, total, success, error400, error_customer, error_system) VALUES (N'AI V1 log sdk', N'/ai/v1/log/sdk', 0, 0, 0, 0, 0);
INSERT INTO api_frequency_stat (name, path, total, success, error400, error_customer, error_system) VALUES (N'Verify face ereception', N'/face-service/face/verify-ereception', 0, 0, 0, 0, 0);
INSERT INTO api_frequency_stat (name, path, total, success, error400, error_customer, error_system) VALUES (N'AI V1 Standard Face Liveness', N'/ai/v1/standard/face/liveness', 0, 0, 0, 0, 0);
INSERT INTO api_frequency_stat (name, path, total, success, error400, error_customer, error_system) VALUES (N'Web v1 ocr id back', N'/ai/v1/web/ocr/id/back', 0, 0, 0, 0, 0);
INSERT INTO api_frequency_stat (name, path, total, success, error400, error_customer, error_system) VALUES (N'Face compare general', N'/ai/v1/face/compare-general', 0, 0, 0, 0, 0);
INSERT INTO api_frequency_stat (name, path, total, success, error400, error_customer, error_system) VALUES (N'Web v4 face liveness', N'/ai/v4/web/face/liveness', 0, 0, 0, 0, 0);
INSERT INTO api_frequency_stat (name, path, total, success, error400, error_customer, error_system) VALUES (N'Ocr back id V2', N'/ai/v2/ocr/id/back', 0, 0, 0, 0, 0);
INSERT INTO api_frequency_stat (name, path, total, success, error400, error_customer, error_system) VALUES (N'Ocr id back', N'/ai/v1/ocr/id/back', 0, 0, 0, 0, 0);
INSERT INTO api_frequency_stat (name, path, total, success, error400, error_customer, error_system) VALUES (N'/ai/v5/face/liveness', N'/ai/v5/face/liveness', 0, 0, 0, 0, 0);
INSERT INTO api_frequency_stat (name, path, total, success, error400, error_customer, error_system) VALUES (N'tt17 compare general', N'/aitt17-service/v1/face/compare-general', 0, 0, 0, 0, 0);
INSERT INTO api_frequency_stat (name, path, total, success, error400, error_customer, error_system) VALUES (N'/faceid-service/v5/face/verify', N'/faceid-service/v5/face/verify', 0, 0, 0, 0, 0);
INSERT INTO api_frequency_stat (name, path, total, success, error400, error_customer, error_system) VALUES (N'Web v4 ocr id front', N'/ai/v4/web/ocr/id/front', 0, 0, 0, 0, 0);
INSERT INTO api_frequency_stat (name, path, total, success, error400, error_customer, error_system) VALUES (N'Face id customer add update', N'/faceid-service/v1/customer/add-update', 0, 0, 0, 0, 0);
INSERT INTO api_frequency_stat (name, path, total, success, error400, error_customer, error_system) VALUES (N'Web v2 ocr id', N'/ai/v2/web/ocr/id', 0, 0, 0, 0, 0);
INSERT INTO api_frequency_stat (name, path, total, success, error400, error_customer, error_system) VALUES (N'tt17 face compare', N'/aitt17-service/v1/face/compare', 0, 0, 0, 0, 0);
INSERT INTO api_frequency_stat (name, path, total, success, error400, error_customer, error_system) VALUES (N'/ai/v5/face/mask', N'/ai/v5/face/mask', 0, 0, 0, 0, 0);
INSERT INTO api_frequency_stat (name, path, total, success, error400, error_customer, error_system) VALUES (N'Web v2 face liveness', N'/ai/v2/web/face/liveness', 0, 0, 0, 0, 0);
INSERT INTO api_frequency_stat (name, path, total, success, error400, error_customer, error_system) VALUES (N'Ocr front id V4', N'/ai/v4/ocr/id/front', 0, 0, 0, 0, 0);
INSERT INTO api_frequency_stat (name, path, total, success, error400, error_customer, error_system) VALUES (N'AI ocr onepage', N'/ai/v1/ocr/onepage', 0, 0, 0, 0, 0);
INSERT INTO api_frequency_stat (name, path, total, success, error400, error_customer, error_system) VALUES (N'Add face v2', N'/face-service/v2/face/add', 0, 0, 0, 0, 0);
INSERT INTO api_frequency_stat (name, path, total, success, error400, error_customer, error_system) VALUES (N'/faceid-service/v2/face/verify', N'/faceid-service/v2/face/verify', 0, 0, 0, 0, 0);
INSERT INTO api_frequency_stat (name, path, total, success, error400, error_customer, error_system) VALUES (N'Face compare V2', N'/ai/v2/face/compare', 0, 0, 0, 0, 0);
INSERT INTO api_frequency_stat (name, path, total, success, error400, error_customer, error_system) VALUES (N'Facetec v1 liveness 3d', N'/ai/v1/face/ext/liveness-3d', 0, 0, 0, 0, 0);
INSERT INTO api_frequency_stat (name, path, total, success, error400, error_customer, error_system) VALUES (N'Photo face compare V4', N'/ai/v4/photo/face/compare', 0, 0, 0, 0, 0);
INSERT INTO api_frequency_stat (name, path, total, success, error400, error_customer, error_system) VALUES (N'VnptVoiceStream StreamToStream', N'vnpt_voice_stream_digit.VnptVoiceStream/StreamToStream', 0, 0, 0, 0, 0);
INSERT INTO api_frequency_stat (name, path, total, success, error400, error_customer, error_system) VALUES (N'AI V2 Standard Face Liveness', N'/ai/v2/standard/face/liveness', 0, 0, 0, 0, 0);
INSERT INTO api_frequency_stat (name, path, total, success, error400, error_customer, error_system) VALUES (N'Face id verify face', N'/faceid-service/v1/face/verify', 0, 0, 0, 0, 0);
INSERT INTO api_frequency_stat (name, path, total, success, error400, error_customer, error_system) VALUES (N'Web v1 ocr id front', N'/ai/v1/web/ocr/id/front', 0, 0, 0, 0, 0);
INSERT INTO api_frequency_stat (name, path, total, success, error400, error_customer, error_system) VALUES (N'Card liveness V2', N'/ai/v2/card/liveness', 0, 0, 0, 0, 0);
INSERT INTO api_frequency_stat (name, path, total, success, error400, error_customer, error_system) VALUES (N'Ocr back id V4', N'/ai/v4/ocr/id/back', 0, 0, 0, 0, 0);
INSERT INTO api_frequency_stat (name, path, total, success, error400, error_customer, error_system) VALUES (N'Web v2 liveness 3d', N'/ai/v2/web/face/liveness-3d', 0, 0, 0, 0, 0);
INSERT INTO api_frequency_stat (name, path, total, success, error400, error_customer, error_system) VALUES (N'/ai/v5/web/face/mask', N'/ai/v5/web/face/mask', 0, 0, 0, 0, 0);
INSERT INTO api_frequency_stat (name, path, total, success, error400, error_customer, error_system) VALUES (N'Ocr id v0', N'/ai/ocr/id', 0, 0, 0, 0, 0);
INSERT INTO api_frequency_stat (name, path, total, success, error400, error_customer, error_system) VALUES (N'CIC customer face add', N'/cic-service/v1/customer-face/add', 0, 0, 0, 0, 0);
INSERT INTO api_frequency_stat (name, path, total, success, error400, error_customer, error_system) VALUES (N'Web v1 face mask', N'/ai/v1/web/face/mask', 0, 0, 0, 0, 0);
INSERT INTO api_frequency_stat (name, path, total, success, error400, error_customer, error_system) VALUES (N'/ai/v1/face/liveness-3d/internal-check', N'/ai/v1/face/liveness-3d/internal-check', 0, 0, 0, 0, 0);
INSERT INTO api_frequency_stat (name, path, total, success, error400, error_customer, error_system) VALUES (N'/ai/v2/face/compare-general-ext', N'/ai/v2/face/compare-general-ext', 0, 0, 0, 0, 0);
INSERT INTO api_frequency_stat (name, path, total, success, error400, error_customer, error_system) VALUES (N'Face check info', N'/face-service/face/check-info', 0, 0, 0, 0, 0);
INSERT INTO api_frequency_stat (name, path, total, success, error400, error_customer, error_system) VALUES (N'Face liveness 3d', N'/ai/v1/face/liveness-3d', 0, 0, 0, 0, 0);
INSERT INTO api_frequency_stat (name, path, total, success, error400, error_customer, error_system) VALUES (N'/ai/v5/classify/id', N'/ai/v5/classify/id', 0, 0, 0, 0, 0);
INSERT INTO api_frequency_stat (name, path, total, success, error400, error_customer, error_system) VALUES (N'Classify id v4', N'/ai/v4/classify/id', 0, 0, 0, 0, 0);
INSERT INTO api_frequency_stat (name, path, total, success, error400, error_customer, error_system) VALUES (N'Ocr id ext', N'/ai/v1/ocr/id/', 0, 0, 0, 0, 0);
INSERT INTO api_frequency_stat (name, path, total, success, error400, error_customer, error_system) VALUES (N'/otptt17-service/v1/otp/verify', N'/otptt17-service/v1/otp/verify', 0, 0, 0, 0, 0);
INSERT INTO api_frequency_stat (name, path, total, success, error400, error_customer, error_system) VALUES (N'ibeta2', N'/ai/v1/ibeta2', 0, 0, 0, 0, 0);
INSERT INTO api_frequency_stat (name, path, total, success, error400, error_customer, error_system) VALUES (N'Classify id v2', N'/ai/v2/classify/id', 0, 0, 0, 0, 0);
INSERT INTO api_frequency_stat (name, path, total, success, error400, error_customer, error_system) VALUES (N'/ai/v5/web/card/liveness', N'/ai/v5/web/card/liveness', 0, 0, 0, 0, 0);
INSERT INTO api_frequency_stat (name, path, total, success, error400, error_customer, error_system) VALUES (N'CIC unit add V1', N'/cic-service/v1/unit/add', 0, 0, 0, 0, 0);
INSERT INTO api_frequency_stat (name, path, total, success, error400, error_customer, error_system) VALUES (N'Web v2 ocr id front', N'/ai/v2/web/ocr/id/front', 0, 0, 0, 0, 0);
INSERT INTO api_frequency_stat (name, path, total, success, error400, error_customer, error_system) VALUES (N'Web v2 face compare', N'/ai/v2/web/face/compare', 0, 0, 0, 0, 0);
INSERT INTO api_frequency_stat (name, path, total, success, error400, error_customer, error_system) VALUES (N'Face add unit', N'/face-service/face/add-unit', 0, 0, 0, 0, 0);
INSERT INTO api_frequency_stat (name, path, total, success, error400, error_customer, error_system) VALUES (N'/ai/v4/face/compare-general-ext', N'/ai/v4/face/compare-general-ext', 0, 0, 0, 0, 0);
INSERT INTO api_frequency_stat (name, path, total, success, error400, error_customer, error_system) VALUES (N'Search face v2', N'/face-service/v2/face/search', 0, 0, 0, 0, 0);
INSERT INTO api_frequency_stat (name, path, total, success, error400, error_customer, error_system) VALUES (N'Web v1 ocr id', N'/ai/v1/web/ocr/id', 0, 0, 0, 0, 0);
INSERT INTO api_frequency_stat (name, path, total, success, error400, error_customer, error_system) VALUES (N'Web v1 face liveness', N'/ai/v1/web/face/liveness', 0, 0, 0, 0, 0);
INSERT INTO api_frequency_stat (name, path, total, success, error400, error_customer, error_system) VALUES (N'Verify face amigo', N'/face-service/face/verify-amigo', 0, 0, 0, 0, 0);
INSERT INTO api_frequency_stat (name, path, total, success, error400, error_customer, error_system) VALUES (N'/ai/v5/web/face/compare', N'/ai/v5/web/face/compare', 0, 0, 0, 0, 0);
INSERT INTO api_frequency_stat (name, path, total, success, error400, error_customer, error_system) VALUES (N'CIC face embedding add', N'/cic-service/v1/face-embedding/add', 0, 0, 0, 0, 0);
INSERT INTO api_frequency_stat (name, path, total, success, error400, error_customer, error_system) VALUES (N'Web v2 face mask', N'/ai/v2/web/face/mask', 0, 0, 0, 0, 0);
INSERT INTO api_frequency_stat (name, path, total, success, error400, error_customer, error_system) VALUES (N'Add face', N'/face-service/face/add', 0, 0, 0, 0, 0);
INSERT INTO api_frequency_stat (name, path, total, success, error400, error_customer, error_system) VALUES (N'AI V4 Web Standard Face Liveness 3D', N'/ai/v4/web/standard/face/liveness-3d', 0, 0, 0, 0, 0);
INSERT INTO api_frequency_stat (name, path, total, success, error400, error_customer, error_system) VALUES (N'Face compare v0', N'/ai/face/compare', 0, 0, 0, 0, 0);
INSERT INTO api_frequency_stat (name, path, total, success, error400, error_customer, error_system) VALUES (N'Web v4 liveness 3d', N'/ai/v4/web/face/liveness-3d', 0, 0, 0, 0, 0);
INSERT INTO api_frequency_stat (name, path, total, success, error400, error_customer, error_system) VALUES (N'Face search disabled faces', N'/face-service/face/search-disabled-faces', 0, 0, 0, 0, 0);
INSERT INTO api_frequency_stat (name, path, total, success, error400, error_customer, error_system) VALUES (N'Classify id', N'/ai/v1/classify/id', 0, 0, 0, 0, 0);
INSERT INTO api_frequency_stat (name, path, total, success, error400, error_customer, error_system) VALUES (N'/faceid-service/v1/customer/list', N'/faceid-service/v1/customer/list', 0, 0, 0, 0, 0);
INSERT INTO api_frequency_stat (name, path, total, success, error400, error_customer, error_system) VALUES (N'AI V4 Standard Face Liveness', N'/ai/v4/standard/face/liveness', 0, 0, 0, 0, 0);
INSERT INTO api_frequency_stat (name, path, total, success, error400, error_customer, error_system) VALUES (N'Card liveness V4', N'/ai/v4/card/liveness', 0, 0, 0, 0, 0);
INSERT INTO api_frequency_stat (name, path, total, success, error400, error_customer, error_system) VALUES (N'Add face amigo', N'/face-service/face/add-amigo', 0, 0, 0, 0, 0);
INSERT INTO api_frequency_stat (name, path, total, success, error400, error_customer, error_system) VALUES (N'/ai/v1/face/compare-general-ext', N'/ai/v1/face/compare-general-ext', 0, 0, 0, 0, 0);
INSERT INTO api_frequency_stat (name, path, total, success, error400, error_customer, error_system) VALUES (N'/ai/v5/face/compare-general', N'/ai/v5/face/compare-general', 0, 0, 0, 0, 0);
INSERT INTO api_frequency_stat (name, path, total, success, error400, error_customer, error_system) VALUES (N'Face liveness V4', N'/ai/v4/face/liveness', 0, 0, 0, 0, 0);
INSERT INTO api_frequency_stat (name, path, total, success, error400, error_customer, error_system) VALUES (N'/ai/v5/face/liveness-3d', N'/ai/v5/face/liveness-3d', 0, 0, 0, 0, 0);
INSERT INTO api_frequency_stat (name, path, total, success, error400, error_customer, error_system) VALUES (N'/ai/v5/web/face/liveness-3d', N'/ai/v5/web/face/liveness-3d', 0, 0, 0, 0, 0);
INSERT INTO api_frequency_stat (name, path, total, success, error400, error_customer, error_system) VALUES (N'tt17 nfc', N'/aitt17-service/v1/nfc', 0, 0, 0, 0, 0);
INSERT INTO api_frequency_stat (name, path, total, success, error400, error_customer, error_system) VALUES (N'CIC customer face verify', N'/cic-service/v1/customer-face/verify', 0, 0, 0, 0, 0);
INSERT INTO api_frequency_stat (name, path, total, success, error400, error_customer, error_system) VALUES (N'Web v4 face mask', N'/ai/v4/web/face/mask', 0, 0, 0, 0, 0);
INSERT INTO api_frequency_stat (name, path, total, success, error400, error_customer, error_system) VALUES (N'Face mask', N'/ai/v1/face/mask', 0, 0, 0, 0, 0);
INSERT INTO api_frequency_stat (name, path, total, success, error400, error_customer, error_system) VALUES (N'Facetec v1 session token', N'/ai/v1/face/session-token', 0, 0, 0, 0, 0);
INSERT INTO api_frequency_stat (name, path, total, success, error400, error_customer, error_system) VALUES (N'Card liveness', N'/ai/v1/card/liveness', 0, 0, 0, 0, 0);
INSERT INTO api_frequency_stat (name, path, total, success, error400, error_customer, error_system) VALUES (N'CIC customer card add V1', N'/cic-service/v1/customer-card/add', 0, 0, 0, 0, 0);
INSERT INTO api_frequency_stat (name, path, total, success, error400, error_customer, error_system) VALUES (N'Add_face', N'/face-service/face/add_face', 0, 0, 0, 0, 0);
INSERT INTO api_frequency_stat (name, path, total, success, error400, error_customer, error_system) VALUES (N'Photo ocr id V2', N'/ai/v2/photo/ocr/id', 0, 0, 0, 0, 0);
INSERT INTO api_frequency_stat (name, path, total, success, error400, error_customer, error_system) VALUES (N'tt17 card liveness', N'/aitt17-service/v1/card/liveness', 0, 0, 0, 0, 0);
INSERT INTO api_frequency_stat (name, path, total, success, error400, error_customer, error_system) VALUES (N'Ocr id V4', N'/ai/v4/ocr/id', 0, 0, 0, 0, 0);
INSERT INTO api_frequency_stat (name, path, total, success, error400, error_customer, error_system) VALUES (N'Save log NFC', N'/ai/v1/nfc', 0, 0, 0, 0, 0);
INSERT INTO api_frequency_stat (name, path, total, success, error400, error_customer, error_system) VALUES (N'Web v1 face compare', N'/ai/v1/web/face/compare', 0, 0, 0, 0, 0);
INSERT INTO api_frequency_stat (name, path, total, success, error400, error_customer, error_system) VALUES (N'STT V1 number sequence', N'/stt-service/v1/number-sequence', 0, 0, 0, 0, 0);
INSERT INTO api_frequency_stat (name, path, total, success, error400, error_customer, error_system) VALUES (N'Ocr id V2', N'/ai/v2/ocr/id', 0, 0, 0, 0, 0);
INSERT INTO api_frequency_stat (name, path, total, success, error400, error_customer, error_system) VALUES (N'Face gender V2', N'/ai/v2/face/gender', 0, 0, 0, 0, 0);
INSERT INTO api_frequency_stat (name, path, total, success, error400, error_customer, error_system) VALUES (N'AI V1 Standard Face Liveness 3D', N'/ai/v1/standard/face/liveness-3d', 0, 0, 0, 0, 0);
INSERT INTO api_frequency_stat (name, path, total, success, error400, error_customer, error_system) VALUES (N'Photo face compare V2', N'/ai/v2/photo/face/compare', 0, 0, 0, 0, 0);
INSERT INTO api_frequency_stat (name, path, total, success, error400, error_customer, error_system) VALUES (N'/ai/v4/face/compare-general', N'/ai/v4/face/compare-general', 0, 0, 0, 0, 0);
INSERT INTO api_frequency_stat (name, path, total, success, error400, error_customer, error_system) VALUES (N'/ai/v5/postcode/matching', N'/ai/v5/postcode/matching', 0, 0, 0, 0, 0);
INSERT INTO api_frequency_stat (name, path, total, success, error400, error_customer, error_system) VALUES (N'Search face', N'/face-service/face/search', 0, 0, 0, 0, 0);
INSERT INTO api_frequency_stat (name, path, total, success, error400, error_customer, error_system) VALUES (N'/faceid-service/v2/customer-card/add', N'/faceid-service/v2/customer-card/add', 0, 0, 0, 0, 0);
INSERT INTO api_frequency_stat (name, path, total, success, error400, error_customer, error_system) VALUES (N'Verify face', N'/face-service/face/verify', 0, 0, 0, 0, 0);
INSERT INTO api_frequency_stat (name, path, total, success, error400, error_customer, error_system) VALUES (N'Face gender', N'/ai/v1/face/gender', 0, 0, 0, 0, 0);
INSERT INTO api_frequency_stat (name, path, total, success, error400, error_customer, error_system) VALUES (N'tt17 id check id', N'/aitt17-service/v1/id-check/id', 0, 0, 0, 0, 0);
INSERT INTO api_frequency_stat (name, path, total, success, error400, error_customer, error_system) VALUES (N'Face one V4', N'/ai/v4/face/one', 0, 0, 0, 0, 0);
INSERT INTO api_frequency_stat (name, path, total, success, error400, error_customer, error_system) VALUES (N'/otptt17-service/v1/otp/gen', N'/otptt17-service/v1/otp/gen', 0, 0, 0, 0, 0);
INSERT INTO api_frequency_stat (name, path, total, success, error400, error_customer, error_system) VALUES (N'Face compare', N'/ai/v1/face/compare', 0, 0, 0, 0, 0);
INSERT INTO api_frequency_stat (name, path, total, success, error400, error_customer, error_system) VALUES (N'tt17 face mask', N'/aitt17-service/v1/face/mask', 0, 0, 0, 0, 0);
INSERT INTO api_frequency_stat (name, path, total, success, error400, error_customer, error_system) VALUES (N'/aitt17-serivce/v1/face/compare', N'/aitt17-serivce/v1/face/compare', 0, 0, 0, 0, 0);
INSERT INTO api_frequency_stat (name, path, total, success, error400, error_customer, error_system) VALUES (N'tt17 face liveness 3d', N'/aitt17-service/v1/face/liveness-3d', 0, 0, 0, 0, 0);
INSERT INTO api_frequency_stat (name, path, total, success, error400, error_customer, error_system) VALUES (N'/faceid-service/v5/customer/add-update', N'/faceid-service/v5/customer/add-update', 0, 0, 0, 0, 0);
INSERT INTO api_frequency_stat (name, path, total, success, error400, error_customer, error_system) VALUES (N'/aitt17-service/v1/customer/add-update', N'/aitt17-service/v1/customer/add-update', 0, 0, 0, 0, 0);
INSERT INTO api_frequency_stat (name, path, total, success, error400, error_customer, error_system) VALUES (N'Face mask V2', N'/ai/v2/face/mask', 0, 0, 0, 0, 0);
INSERT INTO api_frequency_stat (name, path, total, success, error400, error_customer, error_system) VALUES (N'/ai/v5/face/compare', N'/ai/v5/face/compare', 0, 0, 0, 0, 0);
INSERT INTO api_frequency_stat (name, path, total, success, error400, error_customer, error_system) VALUES (N'Face compare V4', N'/ai/v4/face/compare', 0, 0, 0, 0, 0);
INSERT INTO api_frequency_stat (name, path, total, success, error400, error_customer, error_system) VALUES (N'nude check v1 web', N'/ai/v1/web/face/nudecheck', 0, 0, 0, 0, 0);
INSERT INTO api_frequency_stat (name, path, total, success, error400, error_customer, error_system) VALUES (N'Web v4 face compare', N'/ai/v4/web/face/compare', 0, 0, 0, 0, 0);
INSERT INTO api_frequency_stat (name, path, total, success, error400, error_customer, error_system) VALUES (N'Search face ereception', N'/face-service/face/search-ereception', 0, 0, 0, 0, 0);
INSERT INTO api_frequency_stat (name, path, total, success, error400, error_customer, error_system) VALUES (N'CIC face add', N'/cic-service/face/add', 0, 0, 0, 0, 0);
INSERT INTO api_frequency_stat (name, path, total, success, error400, error_customer, error_system) VALUES (N'Face compare ext', N'/ai/v1/face/compare/', 0, 0, 0, 0, 0);
INSERT INTO api_frequency_stat (name, path, total, success, error400, error_customer, error_system) VALUES (N'Face delete', N'/face-service/face/delete', 0, 0, 0, 0, 0);
INSERT INTO api_frequency_stat (name, path, total, success, error400, error_customer, error_system) VALUES (N'Search face amigo', N'/face-service/face/search-amigo', 0, 0, 0, 0, 0);
INSERT INTO api_frequency_stat (name, path, total, success, error400, error_customer, error_system) VALUES (N'Postcode matching', N'/ai/v1/postcode/matching', 0, 0, 0, 0, 0);
INSERT INTO api_frequency_stat (name, path, total, success, error400, error_customer, error_system) VALUES (N'Location percent home', N'/ai/v1/location/percent/home', 0, 0, 0, 0, 0);
INSERT INTO api_frequency_stat (name, path, total, success, error400, error_customer, error_system) VALUES (N'/ai/v5/web/face/liveness', N'/ai/v5/web/face/liveness', 0, 0, 0, 0, 0);
INSERT INTO api_frequency_stat (name, path, total, success, error400, error_customer, error_system) VALUES (N'AI V4 Standard Face Liveness 3D', N'/ai/v4/standard/face/liveness-3d', 0, 0, 0, 0, 0);
INSERT INTO api_frequency_stat (name, path, total, success, error400, error_customer, error_system) VALUES (N'Web v4 ocr id', N'/ai/v4/web/ocr/id', 0, 0, 0, 0, 0);
INSERT INTO api_frequency_stat (name, path, total, success, error400, error_customer, error_system) VALUES (N'Face liveness', N'/ai/v1/face/liveness', 0, 0, 0, 0, 0);
INSERT INTO api_frequency_stat (name, path, total, success, error400, error_customer, error_system) VALUES (N'Ocr front id V2', N'/ai/v2/ocr/id/front', 0, 0, 0, 0, 0);
INSERT INTO api_frequency_stat (name, path, total, success, error400, error_customer, error_system) VALUES (N'Face id customer delete', N'/faceid-service/v1/customer/delete', 0, 0, 0, 0, 0);
INSERT INTO api_frequency_stat (name, path, total, success, error400, error_customer, error_system) VALUES (N'Web v4 card liveness', N'/ai/v4/web/card/liveness', 0, 0, 0, 0, 0);
INSERT INTO api_frequency_stat (name, path, total, success, error400, error_customer, error_system) VALUES (N'nude check v1', N'/ai/v1/face/nudecheck', 0, 0, 0, 0, 0);
INSERT INTO api_frequency_stat (name, path, total, success, error400, error_customer, error_system) VALUES (N'Face id customer card add', N'/faceid-service/v1/customer-card/add', 0, 0, 0, 0, 0);
INSERT INTO api_frequency_stat (name, path, total, success, error400, error_customer, error_system) VALUES (N'AI V1 Web Standard Face Liveness', N'/ai/v1/web/standard/face/liveness', 0, 0, 0, 0, 0);
INSERT INTO api_frequency_stat (name, path, total, success, error400, error_customer, error_system) VALUES (N'Face gender V4', N'/ai/v4/face/gender', 0, 0, 0, 0, 0);
INSERT INTO api_frequency_stat (name, path, total, success, error400, error_customer, error_system) VALUES (N'Face id customer list filter', N'/faceid-service/v1/customer/list-filter', 0, 0, 0, 0, 0);
INSERT INTO api_frequency_stat (name, path, total, success, error400, error_customer, error_system) VALUES (N'AI V2 Web Standard Face Liveness 3D', N'/ai/v2/web/standard/face/liveness-3d', 0, 0, 0, 0, 0);
INSERT INTO api_frequency_stat (name, path, total, success, error400, error_customer, error_system) VALUES (N'Web v1 liveness 3d', N'/ai/v1/web/face/liveness-3d', 0, 0, 0, 0, 0);
INSERT INTO api_frequency_stat (name, path, total, success, error400, error_customer, error_system) VALUES (N'/ai/v5/web/ocr/id', N'/ai/v5/web/ocr/id', 0, 0, 0, 0, 0);
INSERT INTO api_frequency_stat (name, path, total, success, error400, error_customer, error_system) VALUES (N'Photo ocr id', N'/ai/v1/photo/ocr/id', 0, 0, 0, 0, 0);
INSERT INTO api_frequency_stat (name, path, total, success, error400, error_customer, error_system) VALUES (N'/ai/v5/ocr/id', N'/ai/v5/ocr/id', 0, 0, 0, 0, 0);
INSERT INTO api_frequency_stat (name, path, total, success, error400, error_customer, error_system) VALUES (N'Face one V2', N'/ai/v2/face/one', 0, 0, 0, 0, 0);
INSERT INTO api_frequency_stat (name, path, total, success, error400, error_customer, error_system) VALUES (N'AI V2 Standard Face Liveness 3D', N'/ai/v2/standard/face/liveness-3d', 0, 0, 0, 0, 0);
INSERT INTO api_frequency_stat (name, path, total, success, error400, error_customer, error_system) VALUES (N'AI V2 Web Standard Face Liveness', N'/ai/v2/web/standard/face/liveness', 0, 0, 0, 0, 0);
INSERT INTO api_frequency_stat (name, path, total, success, error400, error_customer, error_system) VALUES (N'Ocr id', N'/ai/v1/ocr/id', 0, 0, 0, 0, 0);
INSERT INTO api_frequency_stat (name, path, total, success, error400, error_customer, error_system) VALUES (N'Log video', N'/ai/v1/video', 0, 0, 0, 0, 0);
INSERT INTO api_frequency_stat (name, path, total, success, error400, error_customer, error_system) VALUES (N'SearchFaceK', N'/face-service/face/search-k', 0, 0, 0, 0, 0);
INSERT INTO api_frequency_stat (name, path, total, success, error400, error_customer, error_system) VALUES (N'/ai/v5/nfc', N'/ai/v5/nfc', 0, 0, 0, 0, 0);
INSERT INTO api_frequency_stat (name, path, total, success, error400, error_customer, error_system) VALUES (N'/faceid-service/v1/unit/list-filter', N'/faceid-service/v1/unit/list-filter', 0, 0, 0, 0, 0);
INSERT INTO api_frequency_stat (name, path, total, success, error400, error_customer, error_system) VALUES (N'AI V1 Web Standard Face Liveness 3D', N'/ai/v1/web/standard/face/liveness-3d', 0, 0, 0, 0, 0);
INSERT INTO api_frequency_stat (name, path, total, success, error400, error_customer, error_system) VALUES (N'Face liveness 3d v2', N'/ai/v2/face/liveness-3d', 0, 0, 0, 0, 0);
INSERT INTO api_frequency_stat (name, path, total, success, error400, error_customer, error_system) VALUES (N'Partner ocr', N'/aipn-service/v1/ocr/id', 0, 0, 0, 0, 0);
INSERT INTO api_frequency_stat (name, path, total, success, error400, error_customer, error_system) VALUES (N'Face id customer add', N'/faceid-service/v1/customer/add', 0, 0, 0, 0, 0);
INSERT INTO api_frequency_stat (name, path, total, success, error400, error_customer, error_system) VALUES (N'Face liveness V2', N'/ai/v2/face/liveness', 0, 0, 0, 0, 0);
